# Book I settings and changes of time/weather. Prompts: docs/environment-assets.json.
image bg cassia_home = Transform("images/backgrounds/book-one/cassia-home.png", size=(1920, 1080), fit="cover")
image bg dome = Transform("images/backgrounds/book-one/dome.png", size=(1920, 1080), fit="cover")
image bg echoes = Transform("images/backgrounds/book-one/echoes.png", size=(1920, 1080), fit="cover")
image bg festival = Transform("images/backgrounds/book-one/festival.png", size=(1920, 1080), fit="cover")
image bg home_dusk = Transform("images/backgrounds/book-one/home-dusk.png", size=(1920, 1080), fit="cover")
image bg library = Transform("images/backgrounds/book-one/library.png", size=(1920, 1080), fit="cover")
image bg memorial_plaza = Transform("images/backgrounds/book-one/memorial-plaza.png", size=(1920, 1080), fit="cover")
image bg memory_mural = Transform("images/backgrounds/book-one/memory-mural-v2.png", size=(1920, 1080), fit="cover")
image bg music_room = Transform("images/backgrounds/book-one/music-room.png", size=(1920, 1080), fit="cover")
image bg sage_room = Transform("images/backgrounds/book-one/sage-room.png", size=(1920, 1080), fit="cover")
image bg soren_workshop = Transform("images/backgrounds/book-one/soren-workshop.png", size=(1920, 1080), fit="cover")
image bg treehouse_memory = Transform("images/backgrounds/book-one/treehouse-memory.png", size=(1920, 1080), fit="cover")
image bg waterwheel = Transform("images/backgrounds/book-one/waterwheel.png", size=(1920, 1080), fit="cover")
image bg workshop = Transform("images/backgrounds/book-one/workshop.png", size=(1920, 1080), fit="cover")
image bg construction_room = Transform("images/backgrounds/book-one/construction-room.png", size=(1920, 1080), fit="cover")
