; Native GIMP 2.10 refinements for Lyra and Thalia.
; Run from visual-novel. Original sprites are immutable files in each key folder.
; No generated donor pixels are used by these two local corrections.

(define keys-folder "art/character-keys/")
(define (key-path who name) (string-append keys-folder who "/" name))
(define (save-png image drawable path)
  (file-png-save2 RUN-NONINTERACTIVE image drawable path path 0 9 0 0 0 0 0 0 0))
(define (save-flat image path)
  (let* ((copy (car (gimp-image-duplicate image))) (flat (car (gimp-image-flatten copy))))
    (save-png copy flat path) (gimp-image-delete copy)))
(define (export-mask image mask path)
  (let* ((out (car (gimp-image-new (car (gimp-image-width image)) (car (gimp-image-height image)) GRAY)))
         (layer (car (gimp-layer-new-from-drawable mask out))))
    (gimp-image-insert-layer out layer 0 0)
    (gimp-layer-set-offsets layer 0 0)
    (save-png out layer path)
    (gimp-image-delete out)))
(define (finish image base who)
  (let* ((active (car (gimp-image-get-active-layer image))) (reopened 0) (layers 0) (n 0) (layer 0))
    (gimp-xcf-save RUN-NONINTERACTIVE image active (key-path who "sprite-refined.xcf") (key-path who "sprite-refined.xcf"))
    (save-flat image (key-path who "sprite-refined.png"))
    (gimp-image-delete image)
    (set! reopened (car (gimp-file-load RUN-NONINTERACTIVE (key-path who "sprite-refined.xcf") (key-path who "sprite-refined.xcf"))))
    (save-flat reopened (string-append audit-dir "/" who "-reopened.png"))
    (set! layers (gimp-image-get-layers reopened))
    (while (< n (car layers))
      (set! layer (vector-ref (cadr layers) n))
      (if (= (car (gimp-item-get-lock-content layer)) FALSE) (gimp-item-set-visible layer FALSE))
      (set! n (+ n 1)))
    (save-flat reopened (string-append audit-dir "/" who "-restored.png"))
    (gimp-image-delete reopened)))

(define (pinch-eye image x y width height title maskname)
  (let* ((source (key-path "lyra" "sprite-original.png"))
         (crop (car (gimp-file-load RUN-NONINTERACTIVE source source)))
         (crop-layer (car (gimp-image-get-active-layer crop)))
         (layer 0) (mask 0))
    (gimp-image-crop crop width height x y)
    ; Zero whirl. Positive pinch smoothly contracts eye geometry toward its center.
    (plug-in-whirl-pinch RUN-NONINTERACTIVE crop crop-layer 0 0.22 1.0)
    (set! layer (car (gimp-layer-new-from-drawable crop-layer image)))
    (gimp-image-insert-layer image layer 0 0)
    (gimp-layer-add-alpha layer)
    (gimp-layer-set-offsets layer x y)
    (gimp-layer-resize-to-image-size layer)
    (gimp-item-set-name layer title)
    (gimp-layer-set-mode layer 0)
    (gimp-image-select-ellipse image 2 x y width height)
    (gimp-selection-feather image 1.5)
    (set! mask (car (gimp-layer-create-mask layer 4)))
    (gimp-layer-add-mask layer mask)
    (gimp-selection-none image)
    (export-mask image mask (key-path "lyra" maskname))
    (gimp-image-delete crop)))

(gimp-context-push)
(gimp-context-set-antialias TRUE)
(gimp-context-set-feather FALSE)
(let* ((source (key-path "lyra" "sprite-original.png"))
       (image (car (gimp-file-load RUN-NONINTERACTIVE source source)))
       (base (car (gimp-image-get-active-layer image))))
  (gimp-item-set-name base "Original Lyra sprite - locked")
  (gimp-item-set-lock-content base TRUE)
  (pinch-eye image 452 255 86 72 "Lyra right eye - natural aperture" "mask-eye-viewer-left.png")
  (pinch-eye image 539 241 76 68 "Lyra left eye - natural aperture" "mask-eye-viewer-right.png")
  (finish image base "lyra"))

(let* ((source (key-path "thalia" "sprite-original.png"))
       (image (car (gimp-file-load RUN-NONINTERACTIVE source source)))
       (base (car (gimp-image-get-active-layer image)))
       (layer (car (gimp-layer-copy base TRUE))) (mask 0))
  (gimp-item-set-name base "Original Thalia sprite - locked")
  (gimp-item-set-lock-content base TRUE)
  (gimp-image-insert-layer image layer 0 0)
  (gimp-item-set-lock-content layer FALSE)
  (gimp-item-set-name layer "Thalia deep green iris pigment")
  (gimp-layer-set-mode layer 0)
  ; Only iris pigment. The small central pupil/catchlight regions are excluded.
  (gimp-image-select-polygon image 2 18 (vector 458.5 180.0 460.0 177.0 465.0 175.8 469.4 177.1 469.8 181.0 466.5 183.9 462.0 184.0 459.0 182.5 458.5 180.0))
  (gimp-image-select-polygon image 0 18 (vector 510.5 169.0 512.4 166.2 516.0 165.0 520.0 165.3 522.2 167.0 522.0 170.0 519.2 172.3 514.4 172.8 510.5 169.0))
  (gimp-image-select-ellipse image 1 462.0 177.5 3.1 3.5)
  (gimp-image-select-ellipse image 1 514.8 165.9 3.0 3.5)
  (gimp-selection-feather image 0.35)
  (set! mask (car (gimp-layer-create-mask layer 4)))
  (gimp-layer-add-mask layer mask)
  (gimp-selection-none image)
  (gimp-hue-saturation layer 0 35.0 -4.0 10.0)
  (export-mask image mask (key-path "thalia" "mask-irises.png"))
  (finish image base "thalia"))
(gimp-context-pop)
