; GIMP 2.10.36. Run from visual-novel with Script-Fu batch interpreter.
; Existing paint only: luminance desaturation at 80% opacity, behind tiny masks.
; Keep the prior editable head/torso assembly and every original layer intact.
(define sage-work "../development/visual-novel/art/characters/sage/")
(define sage-out (string-append sage-work "iris-refinement/"))
(define (sage-file name) (string-append sage-out name))
(define (sage-png image layer path)
  (file-png-save2 RUN-NONINTERACTIVE image layer path path 0 9 0 0 0 0 0 0 0))
(define (sage-flat image name)
  (let* ((copy (car (gimp-image-duplicate image))) (flat (car (gimp-image-flatten copy))))
    (sage-png copy flat (sage-file name))
    (gimp-image-delete copy)))
(define (sage-mask-png image drawable name)
  (let* ((copy (car (gimp-image-new (car (gimp-image-width image)) (car (gimp-image-height image)) GRAY)))
         (layer (car (gimp-layer-new-from-drawable drawable copy))))
    (gimp-image-insert-layer copy layer 0 0)
    (sage-png copy layer (sage-file name))
    (gimp-image-delete copy)))
(define (sage-selection-png image name)
  (let* ((channel (car (gimp-selection-save image))))
    (sage-mask-png image channel name)
    (gimp-image-remove-channel image channel)))
(define (sage-detail path name)
  (let* ((image (car (gimp-file-load RUN-NONINTERACTIVE path path)))
         (layer (car (gimp-image-get-active-layer image))))
    (gimp-image-crop image 120 80 442 118)
    (gimp-context-set-interpolation 0)
    (gimp-image-scale image 960 640)
    (sage-png image layer (sage-file name))
    (gimp-image-delete image)))

(gimp-context-push)
(gimp-context-set-antialias TRUE)
(gimp-context-set-feather FALSE)
(let* ((prior (string-append sage-work "sprite-refined.xcf"))
       (source (sage-file "sprite-before.png"))
       (image (car (gimp-file-load RUN-NONINTERACTIVE prior prior)))
       (layer (car (gimp-file-load-layer RUN-NONINTERACTIVE image source)))
       (mask 0) (protected 0) (left-mask 0) (reopened 0) (layers 0) (item 0))
  (sage-flat image "prior-xcf-flattened.png")
  (gimp-image-insert-layer image layer 0 0)
  (gimp-item-set-name layer "Sage gray iris pigment - luminance desaturation 80 percent")
  (gimp-layer-set-mode layer 0)
  (gimp-layer-set-opacity layer 80.0)
  (gimp-item-set-lock-content layer FALSE)

  ; Explicit pupil/catchlight protection, exported independently for verification.
  ; Integer rectangles also preserve the darkest upper iris under each eyelid.
  (gimp-context-set-antialias FALSE)
  (gimp-image-select-rectangle image 2 473 159 9 4)
  (gimp-image-select-rectangle image 0 517 144 8 4)
  (set! protected (car (gimp-selection-save image)))
  (sage-mask-png image protected "mask-protected-pupils-highlights.png")
  (gimp-selection-none image)

  ; Viewer-left iris: its small lower crescent and rim; no sclera or lid paint.
  (gimp-context-set-antialias TRUE)
  (gimp-image-select-polygon image 2 18 (vector
    473.0 159.3 480.0 158.8 482.0 161.0 482.0 164.0
    479.0 166.5 476.0 167.4 474.0 166.4 473.0 164.0 473.0 159.3))
  (gimp-selection-feather image 0.25)
  (gimp-image-select-item image 1 protected)
  (sage-selection-png image "mask-iris-viewer-left.png")
  (set! left-mask (car (gimp-selection-save image)))

  ; Viewer-right iris: preserve the naturally darker upper region.
  (gimp-image-select-polygon image 2 18 (vector
    517.0 144.4 524.7 144.0 526.0 146.0 525.6 148.8
    523.7 150.6 520.0 152.0 518.0 151.0 516.9 148.3 517.0 144.4))
  (gimp-selection-feather image 0.25)
  (gimp-image-select-item image 1 protected)
  (sage-selection-png image "mask-iris-viewer-right.png")
  (gimp-image-select-item image 0 left-mask)
  (set! mask (car (gimp-layer-create-mask layer 4)))
  (gimp-layer-add-mask layer mask)
  (sage-mask-png image mask "mask-irises.png")
  (gimp-selection-none image)
  (gimp-image-remove-channel image protected)
  (gimp-image-remove-channel image left-mask)
  (gimp-drawable-desaturate layer DESATURATE-LUMINANCE)
  (gimp-xcf-save RUN-NONINTERACTIVE image layer (sage-file "sprite-refined.xcf") (sage-file "sprite-refined.xcf"))
  (sage-flat image "sprite-refined.png")
  (gimp-image-delete image)

  ; Reopen the actual saved XCF, then hide only the new correction for restoration.
  (set! reopened (car (gimp-file-load RUN-NONINTERACTIVE (sage-file "sprite-refined.xcf") (sage-file "sprite-refined.xcf"))))
  (sage-flat reopened "xcf-reopened.png")
  (set! layers (gimp-image-get-layers reopened))
  (set! item (vector-ref (cadr layers) 0))
  (gimp-item-set-visible item FALSE)
  (sage-flat reopened "prior-restored.png")
  (gimp-image-delete reopened)
  (sage-detail source "eye-detail-before.png")
  (sage-detail (sage-file "sprite-refined.png") "eye-detail-after.png"))
(gimp-context-pop)
